### ISSUE TITLE
Problema com envio de email.

### ISSUE THREAD

**Issue by Katri-TI** [deivisonarthur/OSC-Magento-Brasil-4-Pro#3]
Ola deivison, toda vez que é efetuada uma compra na loja junto com o email de confirmação da compra é enviado junto um email de confirmação de incrição de newsletter. Creio que deveria ser enviado somente na primeira vez, no entanto esta sendo enviado toda vez que efetuo uma compra!!

**Comment by Vampre** [comment]
Vá no arquivo onepagecheckout.phtml e procure por newsletter. Você vai ver que está configurado para não aparecer e com a opção sempre marcada para assinar!

**Comment by Katri-TI** [comment]
resolvido, Obrigado!

**Comment by monialodo** [comment]
Olá, estou com o mesmo problema aqui, já editei o onepagecheckout.pthml desmarcando a opção checked e deixando como visível mas mesmo assim continua enviando o email de confimação a cada compra! Devo fazer algo mais? Obrigada

**Comment by ghost** [comment]
Olá Pessoal, isso não foi publicado no master pelo Deivison, correto? Pois acabei de baixar este arquivo e o problema continua....

Abraço!
