### ISSUE TITLE
Campos RG e DOB no OSC

### ISSUE THREAD

**Issue by Vampre** [deivisonarthur/OSC-Magento-Brasil-4-Pro#4]
Oi Deivison,

Quando estou no checkout do OSC como pessoa jurídica, todos os campos são salvos normalmente no cadastro.
Agora como Pessoa Física, não salva o RG nem a data de nascimento. Estou tentando arrumar aqui sem sucesso.

Onde preciso mexer para que salve estes campos?

Valeu! Abraço.

**Comment by luizfernandotech** [comment]
Boa tarde,

Eu tive o mesmo problema e consegui resolver o problema da da ta de nascimento e estou correndo atras da correção para o RG.

Segue abaixo a modificação feita para corrigir o problema da data.

abrir o arquivo:
app/code/local/DeivisonArthur/OnepageCheckout/Model/Type/Geo.php

No método "saveBilling", procure por "unset($data['address_id']);", proximo da linha 337.

Coloque o seguinte trecho de codigo logo abaixo:
if (!empty($data['year']) && !empty($data['month']) && !empty($data['day'])) {
                $data['dob'] = "{$data['year']}-{$data['month']}-{$data['day']}";
            }

Vai ficar assim:

else {
            unset($data['address_id']);
            if (!empty($data['year']) && !empty($data['month']) && !empty($data['day'])) {
                $data['dob'] = "{$data['year']}-{$data['month']}-{$data['day']}";
            }
            $address->addData($data);
        }

Isso ai resolve o problema da data de nascimento que nao salva.
Agora estou trabalhando para descobrir onde corrige o problema do RG.

**Comment by luizfernandotech** [comment]
Sobre o RG nao estar gravando é um problema bem simples. O "name" do input esta errado.

Solução:
Va no arquivo app/design/frontend/base/default/template/onepagecheckout/onepage/billing.phtml, na +- linha 141 e corrija o campo input.

de: 
<input type="text" name="rg" id="billing[rg]"

para:
<input type="text" name="billing[rg]" id="rg"

Pronto o sistema passará a salvar os dados RG.

**Comment by evandrorei** [comment]
Nacocada,

Cara ficou Show, estou com problemas apenas no CPF, como eu faço esse maldito salvar tanto no "CADASTRE-SE" do default do magento quanto no OSC ?? eu so consigo fazer salvar no osc...

tem uma solucao?

**Comment by luizfernandotech** [comment]
Estou com o mesmo problema no CPF. ja consegui corrigir uma parte, mas vou deixar para postar a solucao completa. Arrumei a na tela do OSC nao salvava o CPF (estou utilizando o campo taxvat) e no cadastro sem ser pela tela do OSC tb nao salvava o CPF, ja achei a solicao, falta apenas ver na edição. Devo estar postando amanha tudo que tem que arrumar.

Vou postar aqui: https://github.com/deivisonarthur/OSC-Magento-Brasil-4-Pro/issues/11

**Comment by evandrorei** [comment]
FICAREI MUITO CONTENTE COM A SOLUÇÃO PORQUE ESTou dias e noites tentando e nada, ja ate desconfigurei tudo as opçoes de Habilitado e Desabilitado do Text/Vat e campo CPF, se possivel me mandar um print das config do seu modulo tambem... Uq vc precisar de ajuda me fala...abrção cara, estou no aguardo

**Comment by evandrorei** [comment]
Nacocada, conseguiu mesmo arrumar o lance do cpf? 

abrçãooo

**Comment by luizfernandotech** [comment]
Estou trabalhando em cima.. o modulo está muito cheio de bugs.

**Comment by evandrorei** [comment]
Blz...acha que consegue terminar quando? Se precisar de alguma ajuda me fala :)

**Comment by luizfernandotech** [comment]
Resposta no Topico https://github.com/deivisonarthur/OSC-Magento-Brasil-4-Pro/issues/11

**Comment by claudio5678** [comment]
a última atualização trata dos problemas dessa issue
