### ISSUE TITLE
osc.validation.js not found

### ISSUE THREAD

**Issue by andrekutianski** [deivisonarthur/OSC-Magento-Brasil-4-Pro#48]
OSC-Magento-Brasil-4-Pro e Magento CE 1.8.1 /skin/frontend/base/default/deivison/osc.validation.js 404 not found. Arquivo nao encontrado no repositório. Instalação via github.

**Comment by marcoskoshino** [comment]
Estou com o mesmo problema.

**Comment by tiagobnu** [comment]
Mesmo problema...

**Comment by thalessan** [comment]
Alguém solucionou o problema?

**Comment by mariopacio** [comment]
Será que ninguém poderá responder isso??

**Comment by rafaelstz** [comment]
Eu tirei esse arquivo da chamada e usei esse tutorial para validar do Davison mesmo que tomou como referencia o site Inchoo
http://www.deivison.com.br/blog/2012/11/14/magento-unique-taxvat-atrribute-criando-criterios-de-validacao-e-formatando-formularios/

**Comment by KretzmannJ** [comment]
Amigos acho que foi após o update do magento para 1.9, depois de quebrar muito a cabeça resolvi:
- Limpar o cache (js, pages ALL);
- Recompilei;
  voltou a funfar...
  então removi 4 referências para este cara deivison/osc.validation.js
  Tudo funfando normalmente.
  Tomara que ajude alguém!

**Comment by deivisonarthur** [comment]
Show de bola. Eu nem tinha ciência que tinham add esse arquivo ao projeto 

> osc.validation.js

Vou liberar o novo osc ainda essa semana! ;)

Enviado via iPhone

Em 08/08/2014, às 11:21, gwprojetos notifications@github.com escreveu:

**Comment by KretzmannJ** [comment]
Putzzzz... obrigado por todo trabalho envolvido neste módulo!!!
Vou fazer uma doação pro projeto e assim agradecer de verdade!
