### ISSUE TITLE
Conflito mais sério que os da faixa de gaza...

### ISSUE THREAD

**Issue by GustavoSartori** [deivisonarthur/OSC-Magento-Brasil-4-Pro#57]
Baixei a versão corrigida [daqui](https://github.com/deivisonarthur/OSC-Magento-Brasil-4-Pro/issues/40#issuecomment-41265076) e instalei. Fazendo as alterações nos aquivos para chamar os js a partir da pasta do meu tema. O OSC funcionou perfeitamente, tanto para compra por usuário cadastrado quanto para novos clientes e visitantes.

O problema é que aproximadamente 24 horas depois de ter tudo instalado e funcionando, o carrinho de compras da minha loja desapareceu.

![Espaço em branco onde deveria ter um carrinho](https://cloud.githubusercontent.com/assets/8031083/3691911/4cecfa58-1357-11e4-9438-a6d69e3a31f0.png)

Desabilitei o módulo e limpei os caches... nada.
Removi do server todos os arquivos do módulo, limpei o cache e nada!

Já fui ao extremo de pegar os arquivos originais do tema que uso, sem nenhuma alteração, e sobrescrever os editados e NADA!

Alguém pode, por favor, me dar uma luz? Acho que pode ser algum conflito de .js, mas se fosse isso não deveria voltar ao normal depois de desativar/remover o módulo do servidor?

Algum desenvolvedor que não queira me ajudar na parceria, poderia me fazer um orçamento para resolver esse problema?

Tema: Magentech SM Papa
Módulo: SM CartPro
URL: http://myhappyface.com.br

Muito obrigado desde já!!

**Comment by deivisonarthur** [comment]
Brother tenta usar essa versão aqui
https://dl.dropboxusercontent.com/u/138820/OSC-Magento-Brasil-4-Pro-master_corrigido.rar

Foram feitos alguns commits pelo pessoal que usa o OSC, porém to achando
que os commits vieram mais com erro que acertos rs e como já estamos para
lançar a nova versão não mexemos mais na antiga.

o OSC6 já esta pronto para sair do forno, veja um print:
http://inovarti.com.br/osc.png

Ele ira vir totalmente padronizado, com vários fix em alguns bugs que
existiam na versão anterior. Ou seja, estamos preparando algo realmente de
qualidade já que esse módulo é fundamental para todos os lojistas de
Magento e se trata de um módulo usado por grandes cases como: Ricardo
Eletro, 3M, Serasa Experian, Lema21, Puket,....

Para poder passar a todos um produto de qualidade estamos em fase de
homologação do módulo, caso alguém que possua conhecimentos em
desenvolvimento em magento queira contribuir com a nossa homologação me add
no skype (deivisonarthur)

Aproveitando gostaria de apresentar minha empresa a www.inovarti.com.br
segue a apresentação (http://www.inovarti.com.br/inovarti.pdf  e
http://www.inovarti.com.br/inovarti-2.pdf) e um estudo que fiz sobre o
Blackfriday de 2013 onde ressalto o uso do Magento para grandes cases:
http://www.inovarti.com.br/Blackfriday-2013.pdf

Fico no aguardo e obrigado!

Em 24 de julho de 2014 14:29, GustavoSartori notifications@github.com
escreveu:

> Baixei a versão corrigida daqui
> https://github.com/deivisonarthur/OSC-Magento-Brasil-4-Pro/issues/40#issuecomment-41265076
> e instalei. Fazendo as alterações nos aquivos para chamar os js a partir da
> pasta do meu tema. O OSC funcionou perfeitamente, tanto para compra por
> usuário cadastrado quanto para novos clientes e visitantes.
> 
> O problema é que aproximadamente 24 horas depois de ter tudo instalado e
> funcionando, o carrinho de compras da minha loja desapareceu.
> 
> [image: Espaço em branco onde deveria ter um carrinho]
> https://cloud.githubusercontent.com/assets/8031083/3691911/4cecfa58-1357-11e4-9438-a6d69e3a31f0.png
> 
> Desabilitei o módulo e limpei os caches... nada.
> Removi do server todos os arquivos do módulo, limpei o cache e nada!
> 
> Já fui ao extremo de pegar os arquivos originais do tema que uso, sem
> nenhuma alteração, e sobrescrever os editados e NADA!
> 
> Alguém pode, por favor, me dar uma luz? Acho que pode ser algum conflito
> de .js, mas se fosse isso não deveria voltar ao normal depois de
> desativar/remover o módulo do servidor?
> 
> Algum desenvolvedor que não queira me ajudar na parceria, poderia me fazer
> um orçamento para resolver esse problema?
> 
> Tema: Magentech SM Papa
> Módulo: SM CartPro
> URL: http://myhappyface.com.br
> 
> Muito obrigado desde já!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/deivisonarthur/OSC-Magento-Brasil-4-Pro/issues/57.

## 

Atenciosamente

"  É melhor esperar que um programador produtivo torne-se disponível do que
esperar que o primeiro programador disponível torne-se produtivo! "

**Comment by GustavoSartori** [comment]
Obrigado pelo retorno @deivisonarthur, mas foi exatamente essa versão que eu baixei.

Acho que o problema nem é mais no módulo, acho que algo nessa instalação desmembrou minha loja hehehe. Levaram o carrinho pro estacionamento e ele foi atropelado... Não consigo encontrar o problema :/

Mas de qualquer forma, a versão 6 (é isso mesmo?) ta ficando linda de mais!! Só quero ver se vai ser fácil mudar a cor desses cabeçalhos aí :D

Abraço!

**Comment by deivisonarthur** [comment]
Opa então o css desse novo OSC vai vir totalmente padronizado e pegando do
defaul Magento, bastará sobrescreve-lo.

Sobre sua loja me add no skype para eu ver se consigo te ajudar e assim n
pare suas vendas (deivisonarthur) mas recomendo sempre testar em ambiente
dev antes de subir para produção qualquer que seja a alteração.

vlw

Em 24 de julho de 2014 14:53, GustavoSartori notifications@github.com
escreveu:

> Obrigado pelo retorno @deivisonarthur https://github.com/deivisonarthur,
> mas foi exatamente essa versão que eu baixei.
> 
> Acho que o problema nem é mais no módulo, acho que algo nessa instalação
> desmembrou minha loja hehehe. Levaram o carrinho pro estacionamento e ele
> foi atropelado... Não consigo encontrar o problema :/
> 
> Mas de qualquer forma, a versão 6 (é isso mesmo?) ta ficando linda de
> mais!! Só quero ver se vai ser fácil mudar a cor desses cabeçalhos aí :D
> 
> Abraço!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/deivisonarthur/OSC-Magento-Brasil-4-Pro/issues/57#issuecomment-50053610
> .

## 

Atenciosamente

"  É melhor esperar que um programador produtivo torne-se disponível do que
esperar que o primeiro programador disponível torne-se produtivo! "

**Comment by GustavoSartori** [comment]
Falha minha, depois do site 'pronto' não me liguei de deixar uma versão para testes.

Mas então, o @deivisonarthur conseguiu resolver o meu problema - que não tinha NADA a ver com o módulo e sim com um setup muito básico do Magento.

Podem baixar essa versão aqui https://dl.dropboxusercontent.com/u/138820/OSC-Magento-Brasil-4-Pro-master_corrigido.rar que vai dar tudo certo :) 

@deivisonarthur, muito obrigado cara! Salvou meu dia!
